### ISSUE TITLE
PsycoPG2 error on trying to make migrate

### ISSUE THREAD

**Issue by viniciusartur** [okfn-brasil/pedidosanonimos#10]
Could you guys try to reproduce, please?
I tried to hack the error but I'm blocked :(

### Big picture
```
  Given we spin up a vagrant box
  And we install Python 3
  When we clone the project
  And we run the instructions on README.MD
  Then we have a error on PsycoPG2
```

#### The error
```
[vagrant@localhost pedidosanonimos]$ make migrate
python manage.py migrate
/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: server does not support SSL, but SSL was required


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 82, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/vagrant/pedidosanonimos/env/lib64/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: server does not support SSL, but SSL was required

make: *** [migrate] Error 1
```

#### How to reproduce it

1. Create a vagrant machine
```~/projects $ cat Vagrantfile 
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.50.4"
end```

2. vagrant up and vagrant ssh

3. Install Python 3

4. Install Postgres Server, create a user, database and grant permissions.

5. Change database URL on .env

6. run instructions until make migrate

7. make migrate

**Comment by vitorbaptista** [comment]
Você pode tentar mover as linhas https://github.com/okfn-brasil/pedidosanonimos/blob/cbe26571483b5cf0acd838785635d03b57a2c164/web/settings.py#L95-L100 para depois da linha 174? https://github.com/okfn-brasil/pedidosanonimos/blob/cbe26571483b5cf0acd838785635d03b57a2c164/web/settings.py#L172-L175

Segundo https://github.com/heroku/django-heroku/issues/10, eu acho que o `django_heroku` está alterando as configurações do BD. Daí teríamos que alterar as configurações depois dele, pra garantir que ele não as sobrescreva.

**Comment by viniciusartur** [comment]
Funcionou a sua dica!
